---
- set_fact:
    stackhead_syscontainer_volumes: "{{ stackhead_syscontainer_volumes|default([]) + ['/var/run/docker.sock:/var/run/docker.sock'] }}"
  when: stackhead_syscontainer_container_access|bool
- template:
    src: "{{ module_role_path|default(role_path) }}/templates/terraform/system-docker.tf.j2"
    dest: "{{ stackhead__system_tf_root_folder }}/docker_container-{{ stackhead_syscontainer_name }}.tf"
    force: true
  when: ensure == "present"
- file:
    path: "{{ stackhead__system_tf_root_folder }}/docker_container-{{ stackhead_syscontainer_name }}.tf"
    state: absent
  when: ensure == "absent"
