# This task processes the destroy hook placed on container configurations.
---
- name: "Trigger pre-destroy hooks on containers"
  include_tasks: ./steps/sub/execute-destroy-hook.yml
  with_items: "{{ app_config.container.services }}"
  loop_control:
    loop_var: outer_item
  when: item.hooks is defined and item.hooks.before_destroy is defined
