# This task should install the software on the server.
---
- include_tasks: ./steps/sub/migration.yml
- import_role:
      name: getstackhead.virtualization.docker
  vars:
      docker_users: ["{{ ansible_env.SUDO_USER | d('root') }}", "stackhead"]
