- include_tasks: ./steps/sub/migration.yml
- name: "StackHead::Container || Setup system container for service {{ stackhead_syscontainer_name }}"
  include_tasks: "{{ module_role_path | default(role_path) }}/tasks/docker_steps/system-container.yml"
  vars:
    ensure: present
