# This migration renames the old Terraform provider terraform-providers/docker (used at version 2.7.2)
# to the new one. This is required as the provider was transferred into a new repository.
---
- include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks/terraform-replace-provider.yml"
  vars:
    provider_old: terraform-providers/docker
    provider_old_version: "2.7.2"
    provider_new: kreuzwerker/docker
