# This migration ensures Terraform dependencies are up to date, so we use the updated provider.
---
- include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks/terraform-dependencies.yml"
  when: installed_version == "" or (installed_version != "2.9.0" and installed_version is getstackhead.stackhead.isLesserThan("2.9.0"))
  vars:
    installed_version: "{{ lookup('getstackhead.stackhead.tf_provider_version', 'kreuzwerker/docker') }}"
