---
- hosts: localhost
  connection: local
  vars:
    stackhead__roles: "~/.ansible/collections/ansible_collections/getstackhead/stackhead/roles"
  tasks:
    - include_vars: "{{ stackhead__roles }}/stackhead_module_api/testdata/variables.yml"
    - block:
        - name: Generate Docker Terraform file
          import_tasks: "{{ module_role_path | default(role_path) }}/tasks/docker_steps/generate-docker-tf.yml"
          vars:
            stackhead__containerdata_location_global: "./volumes/global/%s" # %s = src
            stackhead__containerdata_location_services: "./volumes/services/%s/%s" # %s = service name, %s = src
      vars:
        module_role_path: ".."
