---
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "../stackhead-repo/ansible/__tests__/variables.yml"
    - block:
        - name: Generate Docker Terraform file
          import_tasks: "../tasks/steps/generate-docker-tf.yml"
          vars:
            stackhead__containerdata_location_global: "./volumes/global/%s" # %s = src
            stackhead__containerdata_location_services: "./volumes/services/%s/%s" # %s = service name, %s = src
      vars:
        role_path: ".."
